baseURL = 'https://press.nordicgamelab.org'
languageCode = 'en-us'
title = 'Nordic Game Lab Press'
theme = "ananke"

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "nordic-game-lab"
  github = "hi5a"
  email = "andrew@nordicgamelab.org"
